name: fresto_apps
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^3.1.0+1
  curved_navigation_bar: ^0.3.1
  random_color: ^1.0.3
  cached_network_image: ^2.0.0
  skeleton_text: ^1.0.0
  fluttertoast: ^3.1.3
  grouped_buttons: ^1.0.4
  flutter_screenutil: ^0.5.3
  uuid: ^2.0.4
  image_picker: ^0.6.3+1
  flutter_secure_storage: ^3.3.1+1
  flutter_dotenv: ^2.1.0
  google_maps_flutter: ^0.5.21+15
  flutter_google_places: ^0.2.3
  google_maps_webservice: ^0.0.16
  location: ^2.3.5
  path_provider: ^1.5.1
  csv: ^4.0.3
  after_layout: ^1.0.7+2
  flutter_picker: ^1.1.0
  flutter_datetime_picker: ^1.3.4
  dotenv: ^2.0.0
  geocoder: ^0.2.1

  firebase_core: ^0.4.2+1
  firebase_auth: ^0.15.0+1
  cloud_firestore: ^0.12.11
  firebase_storage: ^3.1.1

  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  rxdart: ^0.22.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/image_01.png
    - assets/images/image_02.png
    - assets/images/logo.png
    - assets/data/restaurant.csv
    - .env

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf