name: fresto_apps
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^3.1.0+1
  curved_navigation_bar: ^0.3.1
  random_color: ^1.0.3
  cached_network_image: ^1.1.3
  skeleton_text: ^1.0.0
  fluttertoast: ^3.1.3
  grouped_buttons: ^1.0.4
  flutter_screenutil: ^0.5.3
  uuid: ^2.0.4

  firebase_core: ^0.4.2+1
  firebase_auth: ^0.15.0+1
  cloud_firestore: ^0.12.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  rxdart: ^0.22.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/image_01.png
    - assets/images/image_02.png
    - assets/images/logo.png

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf